name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # バージョンを 20 に更新
          node-version: '20'

      - name: Build
        run: |
          cd app/fe
          npm install
          npm run build

      - name: Deploy to S3
        run: aws s3 sync app/fe/dist/ s3://inu-app-frontend-20260612 --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id EI9KCQPEHOWCG --paths "/*"